spring.application.name=notificaciones-service
server.port=8085
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
management.endpoints.web.exposure.include=health

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Al fallar un listener, rechazar sin reencolar para que el mensaje vaya a la DLQ (no bucle infinito)
spring.rabbitmq.listener.simple.default-requeue-rejected=false
